# --- Stage 1: Build Environment ---
FROM mambaorg/micromamba:1.5-focal AS builder
RUN micromamba install -y -n base -c conda-forge \
    python=3.10 numpy scipy pandas openmm parmed mdtraj ambertools openmmforcefields \
    && micromamba clean -afy

# --- Stage 2: Final Runtime Image ---
FROM debian:bookworm-slim
COPY --from=builder /opt/conda /opt/conda
ENV PATH="/opt/conda/bin:$PATH"
ENV AMBERHOME="/opt/conda"
WORKDIR /app

# The filename must match your screenshot exactly
COPY run_openmm_kcx_v5.py /app/run_openmm_kcx_v5.py
RUN chmod +x /app/run_openmm_kcx_v5.py

# Optional: Copy parameter files if they aren't generated by the script
# COPY kcx.frcmod /app/kcx.frcmod
# COPY kcx.lib /app/kcx.lib

# Verification step
RUN python -c "import openmm; print('OpenMM version:', openmm.__version__)"

ENTRYPOINT ["python", "/app/run_openmm_kcx_v5.py"]
